# Generated by Django 3.1.8 on 2021-04-19 22:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Section Title')), ('content', wagtail.core.blocks.RichTextBlock(default='Add your content here!'))])), ('content', wagtail.core.blocks.RichTextBlock(default='Add your content here!')), ('media', wagtail.embeds.blocks.EmbedBlock()), ('file', wagtail.documents.blocks.DocumentChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('faqs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title of your FAQ list (Optional)', required=False)), ('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(label='Question goes here')), ('answer', wagtail.core.blocks.RichTextBlock())])))], label='FAQs'))], blank=True)),
                ('legacyArticleId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
